name: CI

on: [push]

jobs:
  test:
    name: 'Package Tests'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Composer Install
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Style Check
      run: composer test:lint
    - name: Unit Tests
      run: composer test:unit